# Generated by Django 5.2.3 on 2025-07-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderditem_order_orderditem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderditem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderditem',
            name='price',
        ),
    ]
